"""Create daily_checkins table

Revision ID: 82db0dac59f1
Revises: 
Create Date: 2025-10-01 15:48:29.605348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82db0dac59f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('nutrition', sa.Enum('EXCELLENT', 'GOOD', 'OKAY', 'POOR', name='nutritionrating'), nullable=False),
    sa.Column('sleep_quality', sa.Enum('VERY_GOOD', 'GOOD', 'OKAY', 'POOR', name='sleeprating'), nullable=False),
    sa.Column('fitness', sa.Enum('COMPLETED', 'PARTIALLY', 'SKIPPED', name='fitnesscompletion'), nullable=False),
    sa.Column('stress_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='stresslevel'), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_checkins_id'), 'daily_checkins', ['id'], unique=False)
    op.create_index(op.f('ix_daily_checkins_log_date'), 'daily_checkins', ['log_date'], unique=False)
    op.create_index(op.f('ix_daily_checkins_user_id'), 'daily_checkins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_checkins_user_id'), table_name='daily_checkins')
    op.drop_index(op.f('ix_daily_checkins_log_date'), table_name='daily_checkins')
    op.drop_index(op.f('ix_daily_checkins_id'), table_name='daily_checkins')
    op.drop_table('daily_checkins')
    # ### end Alembic commands ###
