# File: bennyai_test.yml
# Author: William O'Brien
# Description: GitHub Actions workflow for running tests on the benny-ai-service.
#   This workflow automatically runs unit tests whenever code is pushed to or
#   a pull request is made against the main branch.

name: Run Tests for benny-ai-service

# Define when this workflow should run
on:
  push:
    branches: [ main ]      # Run on pushes to main branch
  pull_request:
    branches: [ main ]      # Run on pull requests targeting main branch

# Define the jobs to run
jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
      # Download the repository code to the runner
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment with specified version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install required Python packages from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r benny-ai-service/requirements.txt

      # Execute the unit tests in the benny-ai-service directory
      - name: Run tests
        working-directory: benny-ai-service
        run: python -m unittest test_benny.py