name: Run Unittests for benny-ai-service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: Install Python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pytest  # or remove if using unittest

      # - name: Run test.py with pytest
      #   run: |
      #     pytest test.py

      # # Setup Node.js
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'

      # - name: Run test.js
      #   run: |
      #     node test.js

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r benny-ai-service/requirements.txt

      - name: Run tests
        working-directory: benny-ai-service
        run: python -m unittest test_benny.py
